---
title: "TeenGrowth Vignette"
author: "Katherine Schaumberg "
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
        fig_caption: yes
vignette: >
  %\VignetteIndexEntry{eBMIz Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Create bmi forecast

```{r}
library(TeenGrowth)
library(tidyr)
 

```

## Plot bmi forecast
```{r, warning=FALSE, message=FALSE}
plot_eBMI(clean_data = clean_data(test_data_3,
                                id_col_name = 'participant', 
                                           age_col_name = 'age',
                                           sex_col_name = 'sex',
                                           bmiz_col_name = 'bmiz', 
                                           adult_height = 'adult_ht_in'),
          forecast_data = clean_and_process(data = test_data_3, 
                                           id_col_name = 'participant', 
                                           age_col_name = 'age',
                                           sex_col_name = 'sex',
                                           bmiz_col_name = 'bmiz', 
                                           adult_height = 'adult_ht_in'), model = 'ARIMA', ci = '95%', px = 2)

```
